### ISSUE TITLE
Type of basemodel is evaluated as 'str' when using `from __future__ import annotations`

### ISSUE THREAD

**Issue by cpdeethree** [edornd/clidantic#13]
**Describe the bug**
`from __future__ import annotations` is a nice thing for many reasons, especially when using MyPy. See PEP 563: https://mypy.readthedocs.io/en/stable/runtime_troubles.html

But it causes an issue with this library. The library expects a subclass of BaseModel, but with this change above, types are evaluated to strings automatically and need to be eval()'ed to unwrap them for appropriate discovery.

**To Reproduce**
1. Go to test_types.py
2. Add line to top of file: `from __future__ import annotations`
3. Run `poetry run pytest -s`
4. See error `AssertionError: Configuration must be a pydantic model`

**Expected behavior**
I should be able to use `from __future__ import annotations`

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Macos
 - Python Version 3.10
 - Library Version 0.0.0

**Additional context**
This is fairly easily resolved by changing [this line](https://github.com/edornd/clidantic/blob/main/clidantic/core.py#L144) to be

```python
func_arguments = inspect.signature(f, eval_str = True).parameters
```

I am happy to submit a PR if you agree. Here's the relevant discussion between Larry, Guido and others about this feature: https://bugs.python.org/issue43817

**Comment by edornd** [comment]
Hey @cpdeethree! Thanks for the thorough explanation, makes perfect sense. I'd have accepted the pull request, but given the tiny change I directly added it myself. The CI is not really working properly, but the fix is there 👍 I'll try to complete the fix properly in the following days.

**Comment by c-p-b** [comment]
Great! I will go ahead and close this then
